name: CD Workflow

on:
  pull_request:
    types:
      - opened
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Deploy to TestPyPI
        env:
          API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --repository testpypi --skip-existing dist/* -u __token__ -p $API_TOKEN
