name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  lint-format-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 pytest coverage pytest-cov

      - name: Lint code
        run: |
          flake8 app tests || true

      - name: Check formatting
        run: |
          black --check app tests || true

      - name: Format code
        if: github.event_name == 'push'
        run: |
          black app tests || true

      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings -q --tb=short --cov=app --cov-report=term > coverage-report.txt

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: coverage-report
          path: coverage-report.txt

      - name: Upload linting and formatting report
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: lint-format-report
          path: |
            .flake8
            .tox
            black-report.txt
